### ISSUE TITLE
Raised clock frequency affects logging output (SWO) with println!

### ISSUE THREAD

**Issue by elnenez** [dhylands/drone-weact-blinky#1]
Hello:

I've been testing this project and found that println! messages don't appear when logging with 'just log'.

If a comment line 40 in root.rs:
//sysclk_regs.raise_system_frequency().root_wait();

I get the log output 'sec' approximately every 10 seconds.

Kind regards.

**Comment by elnenez** [comment]
It just needed to update swo prescaler after raise_system_frequency():

drone_cortexm::swo::flush();
drone_cortexm::swo::update_prescaler(sysclk_regs.clock() / drone_core::log::baud_rate!() - 1);

**Comment by elnenez** [comment]
Fixed with commit c72a5130d85cee10000f386e559ce4e1b4fb0ce0.

**Comment by davehylands** [comment]
Thanks. It looks like you can also get this by changing the `reset-freq` in the Drone.toml file to be `96000000`. When the `just log` command is run, it sets a bunch of registers via gdb, including:
```
set {int} 0xE0040010  =  96000000 / 115200 - 1
```
which is essentially what your change does (the 96000000 comes from the Drone.toml file). Since the code isn't setting the other SWO registers, I think I'd rather leave it with gdb doing all of the register manipulations for now.
